notepad/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from notes.views import note_list_view, finish_item, delete_item, recover_item

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', note_list_view, name='note-list'),
    path('finish-item/<id>/',finish_item, name='finished-item-list'),
    path('recover-item/<id>/',recover_item, name='recover-item-list'),
    path('delete-item/<id>/',delete_item, name='delete-item-list'),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notes/models.py
from django.db import models
from django.shortcuts import redirect, reverse
LABEL_CHOICES = (
('P','primary'),
('SE','secondary'),
('S','success'),
('D','danger'),
('W','warning'),
('I','info'),
('L','light'),
('D','dark')

)
# Create your models here.
class Note(models.Model):
    title = models.CharField(max_length=100)
    due_date = models.DateTimeField()
    label = models.CharField(choices=LABEL_CHOICES, max_length=2)
    finished = models.BooleanField(default=False)

    def __str__(self):
        return self.title
    
    def get_finish_item_url(self):
        return reverse('finished-item-list', kwargs={
            'id':self.id
        })

    def get_recover_item_url(self):
        return reverse('recover-item-list', kwargs={
            'id':self.id
        })

    def get_delete_item_url(self):
        return reverse('delete-item-list', kwargs={
            'id':self.id
        })



notes/forms.py
from django import forms
from .models import Note
class NoteFormModel(forms.ModelForm):
    
    class Meta:
        model = Note
        fields = ("title","due_date","label")

notes/views.py
from django.shortcuts import render, get_object_or_404, redirect
from notes.models import Note
from notes.forms import NoteFormModel

# Create your views here.
def note_list_view(request):
    form = NoteFormModel()
    if request.method == "POST":
        form = NoteFormModel(request.POST)
        if form.is_valid():
            form.save()
            return redirect('note-list')
    to_do_list = Note.objects.filter(finished=False)
    finished_list = Note.objects.filter(finished=True)
    context = {
        'to_do_list': to_do_list,
        'finished_list': finished_list,
        'form' : form,
    }
    return render(request, "note_list.html", context)

def finish_item(request, id):
    note = get_object_or_404(Note, id=id)
    note.finished = True
    note.save()
    return redirect('note-list')

def recover_item(request, id):
    note = get_object_or_404(Note, id=id)
    note.finished = False
    note.save()
    return redirect('note-list')

def delete_item(request, id):
    note = get_object_or_404(Note, id=id)
    note.delete()
    return redirect('note-list')

templates/base.html

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.6">
    <title>Starter Template · Bootstrap</title>

    <!-- CSS -->
    
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <!-- Favicons -->
-config" content="/docs/4.4/assets/img/favicons/browserconfig.xml">
<meta name="theme-color" content="#563d7c">


    <!-- Custom styles for this template -->
   
  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark ">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
        <div class="dropdown-menu" aria-labelledby="dropdown01">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
      <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

<main role="main" class="container">

{% block content %}

{% endblock content %}

<!-- jQuery and JS bundle w/ Popper.js -->
<script src="https://kit.fontawesome.com/f0b87eaab4.js" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

</body>
</html>

templates/note_list.html
{% extends 'base.html' %}

{% block content %}
<style>
        h4 {
            position: relative;
        }
        .icons {
        position: absolute;
        right: 5px;
        }
</style>

<div class="text-center" mt-3>
   <h2> To-Do List
    
        <a class="btn btn-primary" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
        <i class="fas fa-plus"></i>
        </a> </h2>
   <hr />
   </div>
   <div class="collapse" id="collapseExample">
    <div class="card card-body">
        <form method="post">

            {% csrf_token %}

            <div class="form-group">
            <label for="id_title">Title</label>
            {{ form.title }}
            
            </div>
            <div class="form-group">
            <label for="id_due_date">Due Date</label>
            {{ form.due_date }}
            </div>
            <div class="form-group form-check">
                <label  for="id_label">Label</label>
                {{ form.label }}
            
            </div>
            <button type="submit" class="btn btn-primary">Create</button>
  </form>
    </div>
  </div>
   

  

   
   <div class="row">
   {% for note in to_do_list %}
   <div class="col-12">
    <div class="card">
        <div class="card-body">
            <h4>{{note.title}}<span class="badge badge-{{note.get_label_display}}">

                    {{ note.due_date }}

    </span>
    <span class="icons"> 
         <a href="{{note.get_finish_item_url}}"> <i class="fas fa-check"></i></a>
         <a href="{{note.get_delete_item_url}}"> <i class="fas fa-trash" style="color:red;"></i></a>
     </span>
    </h4>
  </div>
</div>
    </div>
{% endfor %}
</div>

<div class="text-center" mt-3>
   <h2> Finished List </h2>
   <hr />
   </div>
   <div class="row">
   {% for note in finished_list %}
   <div class="col-12">
    <div class="card">
        <div class="card-body">
            <h4>{{note.title}}<span class="badge badge-{{note.get_label_display}}">

                    {{ note.due_date }}

    </span>
     <span class="icons"> 
         <a href="{{note.get_recover_item_url}}"> <i class="fas fa-times"></i> </a>
         <a href="{{note.get_delete_item_url}}"> <i class="fas fa-trash" style="color:red;"></i> </a>
     </span> 
    </h4>
  </div>
</div>
    </div>
{% endfor %}
</div>

{% endblock content %}
 